// ---------------------------------------------------------------------------
// Counterfactual Shadow Engine
//
// For EVERY signal generated by any strategy, records ideal and realistic
// execution outcomes, decomposes PnL into edge/cost components, attributes
// signal vs execution quality, tests viability at different latencies,
// and computes parameter sensitivity.
// ---------------------------------------------------------------------------

import { getLogger } from '../utils/logger.js';
import { now } from '../utils/time.js';
import { clamp } from '../utils/math.js';
import { mean } from '../utils/statistics.js';
import type { TradeSignal, DecayModel } from '../ledger/types.js';
import { computeEvAtT } from '../ledger/types.js';
import type { OrderBook } from '../state/types.js';

const log = getLogger('shadow_engine');

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Price snapshot at the moment a signal fires. */
export interface PriceSnapshot {
  mid: number;
  best_bid: number;
  best_ask: number;
  spread: number;
  spread_bps: number;
  microprice: number;
  book_depth_bid: number;
  book_depth_ask: number;
}

/** Full counterfactual record for one signal. */
export interface ShadowRecord {
  signal_id: string;
  strategy_id: string;
  market_id: string;
  token_id: string;
  direction: 'BUY' | 'SELL';
  signal_timestamp: number;

  // Prices
  ideal_entry_price: number;          // mid at signal time (zero latency)
  realistic_entry_price: number;      // price after expected execution delay
  price_at_signal: PriceSnapshot;

  // PnL decomposition (per unit)
  ideal_pnl: number;                 // zero latency, zero costs
  signal_quality_pnl: number;        // zero latency, real costs
  actual_pnl: number;                // real latency, all costs

  // Cost decomposition
  edge_gross: number;
  cost_latency: number;
  cost_slippage: number;
  cost_fees: number;
  cost_market_impact: number;
  edge_net: number;

  // Signal vs execution attribution
  signal_correct: boolean;            // did price move in predicted direction?
  signal_alpha: number;               // ideal_pnl (signal quality)
  execution_alpha: number;            // actual_pnl - ideal_pnl (execution quality)
  attribution: 'good_signal_good_exec'
    | 'good_signal_bad_exec'
    | 'bad_signal_good_exec'
    | 'bad_signal_bad_exec';

  // Viability at different latencies
  viability: Record<number, boolean>; // {1000: true, 2000: true, ...}

  // Parameter sensitivity
  sensitivity: ParameterSensitivity;

  // Metadata
  ev_estimate: number;
  ev_after_costs: number;
  signal_strength: number;
  size_requested: number;
  decay_model: DecayModel;
  holding_period_ms: number;

  // Outcome (filled in when we have post-signal price data)
  outcome_price: number | null;       // price at holding_period after signal
  outcome_timestamp: number | null;
  resolved: boolean;
}

export interface ParameterSensitivity {
  /** PnL if entry threshold were ±10% tighter/looser. */
  threshold_minus_10pct_pnl: number;
  threshold_plus_10pct_pnl: number;
  /** PnL if size were ±50%. */
  size_minus_50pct_pnl: number;
  size_plus_50pct_pnl: number;
  /** Is signal robust? (positive PnL at all perturbations) */
  robust: boolean;
}

/** Latency buckets used for viability analysis. */
const LATENCY_BUCKETS_MS = [1_000, 2_000, 3_000, 5_000, 10_000, 15_000, 20_000, 30_000] as const;

const FEE_RATE = 0.02;

/** Default slippage model: slippage as fraction of spread per $100 size. */
const SLIPPAGE_PER_100_USD = 0.001;

/** Default market impact: fraction of mid per $100 size. */
const IMPACT_PER_100_USD = 0.0005;

// ---------------------------------------------------------------------------
// Price provider interface — DI for price lookups
// ---------------------------------------------------------------------------

export interface PriceProvider {
  /** Get the order book for a token at a specific time (or current if null). */
  getBookAt(tokenId: string, timestampMs: number | null): OrderBook | null;
  /** Get the mid price at a specific time. */
  getMidAt(tokenId: string, timestampMs: number | null): number | null;
}

// ---------------------------------------------------------------------------
// Module state
// ---------------------------------------------------------------------------

const shadowRecords: Map<string, ShadowRecord> = new Map();
const recordsByStrategy: Map<string, string[]> = new Map();
const recordsByMarket: Map<string, string[]> = new Map();

let priceProvider: PriceProvider | null = null;

export function setPriceProvider(provider: PriceProvider): void {
  priceProvider = provider;
}

export function resetShadowEngine(): void {
  shadowRecords.clear();
  recordsByStrategy.clear();
  recordsByMarket.clear();
  priceProvider = null;
}

// ---------------------------------------------------------------------------
// Core: record a signal
// ---------------------------------------------------------------------------

/**
 * Record a new signal in the shadow engine.
 * This captures the ideal entry price and pre-computes cost estimates.
 * Call `resolveSignal` later when outcome price is known.
 */
export function recordSignal(
  signal: TradeSignal,
  book: OrderBook,
  measuredLatencyMs: number,
): ShadowRecord {
  const snapshot = capturePrice(book);
  const idealEntry = snapshot.mid;

  // Simulate realistic entry after execution delay
  const realisticEntry = simulateRealisticEntry(
    signal, snapshot, measuredLatencyMs,
  );

  // Cost decomposition (per unit, estimated before outcome)
  const latencyCost = Math.abs(realisticEntry - idealEntry);
  const slippageCost = estimateSlippage(signal.size_requested, snapshot.spread);
  const feeCost = FEE_RATE;
  const impactCost = estimateMarketImpact(signal.size_requested, snapshot.mid);

  const edgeGross = signal.ev_estimate + feeCost; // gross edge before any costs
  const edgeNet = edgeGross - latencyCost - slippageCost - feeCost - impactCost;

  // Viability at different latencies
  const viability = computeViability(signal, snapshot);

  // Parameter sensitivity (preliminary — refined on resolution)
  const sensitivity = computeSensitivity(signal, snapshot, edgeGross);

  const record: ShadowRecord = {
    signal_id: signal.signal_id,
    strategy_id: signal.strategy_id,
    market_id: signal.market_id,
    token_id: signal.token_id,
    direction: signal.direction,
    signal_timestamp: signal.timestamp,

    ideal_entry_price: idealEntry,
    realistic_entry_price: realisticEntry,
    price_at_signal: snapshot,

    // Preliminary — updated on resolution
    ideal_pnl: 0,
    signal_quality_pnl: 0,
    actual_pnl: 0,

    edge_gross: edgeGross,
    cost_latency: latencyCost,
    cost_slippage: slippageCost,
    cost_fees: feeCost,
    cost_market_impact: impactCost,
    edge_net: edgeNet,

    signal_correct: false,
    signal_alpha: 0,
    execution_alpha: 0,
    attribution: 'bad_signal_bad_exec',

    viability: viability as Record<number, boolean>,
    sensitivity,

    ev_estimate: signal.ev_estimate,
    ev_after_costs: signal.ev_after_costs,
    signal_strength: signal.signal_strength,
    size_requested: signal.size_requested,
    decay_model: signal.decay_model,
    holding_period_ms: signal.expected_holding_period_ms,

    outcome_price: null,
    outcome_timestamp: null,
    resolved: false,
  };

  shadowRecords.set(signal.signal_id, record);
  indexRecord(recordsByStrategy, signal.strategy_id, signal.signal_id);
  indexRecord(recordsByMarket, signal.market_id, signal.signal_id);

  log.debug({
    signal_id: signal.signal_id,
    strategy: signal.strategy_id,
    ideal_entry: idealEntry.toFixed(4),
    realistic_entry: realisticEntry.toFixed(4),
    edge_gross: edgeGross.toFixed(4),
    edge_net: edgeNet.toFixed(4),
  }, 'Shadow record created');

  return record;
}

// ---------------------------------------------------------------------------
// Resolve: when we know the outcome price
// ---------------------------------------------------------------------------

/**
 * Resolve a shadow record with the actual outcome price.
 * Computes ideal/signal-quality/actual PnL and attribution.
 */
export function resolveSignal(
  signalId: string,
  outcomePrice: number,
  outcomeTimestamp: number,
): ShadowRecord | null {
  const record = shadowRecords.get(signalId);
  if (!record || record.resolved) return null;

  record.outcome_price = outcomePrice;
  record.outcome_timestamp = outcomeTimestamp;
  record.resolved = true;

  const dir = record.direction === 'BUY' ? 1 : -1;

  // (1) Ideal PnL: zero latency, zero costs
  record.ideal_pnl = dir * (outcomePrice - record.ideal_entry_price);

  // (2) Signal quality PnL: zero latency, real costs (fees only)
  record.signal_quality_pnl = record.ideal_pnl - FEE_RATE;

  // (3) Actual PnL: real latency, all costs
  record.actual_pnl = dir * (outcomePrice - record.realistic_entry_price)
    - record.cost_fees - record.cost_slippage - record.cost_market_impact;

  // Re-compute cost decomposition with actual data
  record.cost_latency = Math.abs(record.realistic_entry_price - record.ideal_entry_price);
  record.edge_gross = record.ideal_pnl;
  record.edge_net = record.actual_pnl;

  // (5) Signal vs execution attribution
  record.signal_correct = record.ideal_pnl > 0;
  record.signal_alpha = record.ideal_pnl;
  record.execution_alpha = record.actual_pnl - record.ideal_pnl;

  if (record.signal_correct && record.actual_pnl > 0) {
    record.attribution = 'good_signal_good_exec';
  } else if (record.signal_correct && record.actual_pnl <= 0) {
    record.attribution = 'good_signal_bad_exec';
  } else if (!record.signal_correct && record.actual_pnl > 0) {
    record.attribution = 'bad_signal_good_exec';
  } else {
    record.attribution = 'bad_signal_bad_exec';
  }

  // Re-compute sensitivity with actual outcome
  record.sensitivity = computeSensitivityResolved(record);

  log.debug({
    signal_id: signalId,
    ideal_pnl: record.ideal_pnl.toFixed(4),
    actual_pnl: record.actual_pnl.toFixed(4),
    attribution: record.attribution,
  }, 'Shadow record resolved');

  return record;
}

// ---------------------------------------------------------------------------
// Queries
// ---------------------------------------------------------------------------

export function getRecord(signalId: string): ShadowRecord | undefined {
  return shadowRecords.get(signalId);
}

export function getRecordsByStrategy(strategyId: string): ShadowRecord[] {
  const ids = recordsByStrategy.get(strategyId) ?? [];
  return ids.map(id => shadowRecords.get(id)!).filter(Boolean);
}

export function getRecordsByMarket(marketId: string): ShadowRecord[] {
  const ids = recordsByMarket.get(marketId) ?? [];
  return ids.map(id => shadowRecords.get(id)!).filter(Boolean);
}

export function getAllRecords(): ShadowRecord[] {
  return Array.from(shadowRecords.values());
}

export function getResolvedRecords(): ShadowRecord[] {
  return getAllRecords().filter(r => r.resolved);
}

// ---------------------------------------------------------------------------
// Counterfactual report
// ---------------------------------------------------------------------------

export interface CounterfactualReport {
  strategy_id: string;
  total_signals: number;
  resolved_signals: number;
  avg_ideal_pnl: number;
  avg_signal_quality_pnl: number;
  avg_actual_pnl: number;
  avg_edge_gross: number;
  avg_edge_net: number;
  cost_breakdown: {
    avg_latency: number;
    avg_slippage: number;
    avg_fees: number;
    avg_market_impact: number;
  };
  signal_accuracy: number;          // fraction where signal_correct = true
  attribution_counts: Record<string, number>;
  avg_signal_strength: number;
  avg_ev_estimate: number;
}

export function reportCounterfactual(strategyId: string): CounterfactualReport {
  const records = getRecordsByStrategy(strategyId);
  const resolved = records.filter(r => r.resolved);

  if (resolved.length === 0) {
    return {
      strategy_id: strategyId,
      total_signals: records.length,
      resolved_signals: 0,
      avg_ideal_pnl: 0,
      avg_signal_quality_pnl: 0,
      avg_actual_pnl: 0,
      avg_edge_gross: 0,
      avg_edge_net: 0,
      cost_breakdown: { avg_latency: 0, avg_slippage: 0, avg_fees: 0, avg_market_impact: 0 },
      signal_accuracy: 0,
      attribution_counts: {},
      avg_signal_strength: 0,
      avg_ev_estimate: 0,
    };
  }

  const attrs: Record<string, number> = {};
  for (const r of resolved) {
    attrs[r.attribution] = (attrs[r.attribution] ?? 0) + 1;
  }

  return {
    strategy_id: strategyId,
    total_signals: records.length,
    resolved_signals: resolved.length,
    avg_ideal_pnl: mean(resolved.map(r => r.ideal_pnl)),
    avg_signal_quality_pnl: mean(resolved.map(r => r.signal_quality_pnl)),
    avg_actual_pnl: mean(resolved.map(r => r.actual_pnl)),
    avg_edge_gross: mean(resolved.map(r => r.edge_gross)),
    avg_edge_net: mean(resolved.map(r => r.edge_net)),
    cost_breakdown: {
      avg_latency: mean(resolved.map(r => r.cost_latency)),
      avg_slippage: mean(resolved.map(r => r.cost_slippage)),
      avg_fees: mean(resolved.map(r => r.cost_fees)),
      avg_market_impact: mean(resolved.map(r => r.cost_market_impact)),
    },
    signal_accuracy: resolved.filter(r => r.signal_correct).length / resolved.length,
    attribution_counts: attrs,
    avg_signal_strength: mean(resolved.map(r => r.signal_strength)),
    avg_ev_estimate: mean(resolved.map(r => r.ev_estimate)),
  };
}

// ---------------------------------------------------------------------------
// Viability report
// ---------------------------------------------------------------------------

export interface ViabilityReport {
  strategy_id: string;
  total_resolved: number;
  latency_viability: Record<number, {
    viable_count: number;
    viable_pct: number;
    avg_pnl_at_latency: number;
  }>;
}

export function reportViability(strategyId?: string): ViabilityReport[] {
  const strategies = strategyId
    ? [strategyId]
    : Array.from(recordsByStrategy.keys());

  return strategies.map(sid => {
    const resolved = getRecordsByStrategy(sid).filter(r => r.resolved);

    const latencyViability: Record<number, { viable_count: number; viable_pct: number; avg_pnl_at_latency: number }> = {};

    for (const bucket of LATENCY_BUCKETS_MS) {
      const viableRecords = resolved.filter(r => r.viability[bucket] === true);
      const pnls = viableRecords.map(r => {
        // Estimate PnL at this specific latency
        const latencyCost = bucket > 0
          ? computeEvAtT(r.decay_model, bucket) - computeEvAtT(r.decay_model, 0) + r.cost_fees
          : r.actual_pnl;
        return r.ideal_pnl - Math.abs(latencyCost);
      });

      latencyViability[bucket] = {
        viable_count: viableRecords.length,
        viable_pct: resolved.length > 0 ? viableRecords.length / resolved.length : 0,
        avg_pnl_at_latency: pnls.length > 0 ? mean(pnls) : 0,
      };
    }

    return {
      strategy_id: sid,
      total_resolved: resolved.length,
      latency_viability: latencyViability,
    };
  });
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

function capturePrice(book: OrderBook): PriceSnapshot {
  return {
    mid: book.mid,
    best_bid: book.bids[0]?.[0] ?? 0,
    best_ask: book.asks[0]?.[0] ?? 0,
    spread: book.spread,
    spread_bps: book.spread_bps,
    microprice: book.microprice,
    book_depth_bid: sumDepth(book.bids),
    book_depth_ask: sumDepth(book.asks),
  };
}

function sumDepth(levels: [number, number][]): number {
  let d = 0;
  for (const [, size] of levels) d += size;
  return d;
}

function simulateRealisticEntry(
  signal: TradeSignal,
  snapshot: PriceSnapshot,
  measuredLatencyMs: number,
): number {
  // Price moves during execution delay — use decay model as proxy
  const evDecay = computeEvAtT(signal.decay_model, measuredLatencyMs);
  const evLoss = signal.decay_model.initial_ev - evDecay;

  // Realistic entry is ideal entry adjusted for EV loss
  if (signal.direction === 'BUY') {
    return snapshot.mid + evLoss + snapshot.spread / 2;
  } else {
    return snapshot.mid - evLoss - snapshot.spread / 2;
  }
}

function estimateSlippage(sizeRequested: number, spread: number): number {
  return SLIPPAGE_PER_100_USD * (sizeRequested / 100) * spread;
}

function estimateMarketImpact(sizeRequested: number, mid: number): number {
  if (mid <= 0) return 0;
  return IMPACT_PER_100_USD * (sizeRequested / 100);
}

function computeViability(
  signal: TradeSignal,
  snapshot: PriceSnapshot,
): Record<number, boolean> {
  const result: Record<number, boolean> = {};
  const grossEv = signal.ev_estimate + FEE_RATE; // un-cost the ev_after_costs

  for (const latencyMs of LATENCY_BUCKETS_MS) {
    // EV remaining after decay at this latency
    const evRemaining = computeEvAtT(signal.decay_model, latencyMs);
    // Costs at this latency
    const costs = FEE_RATE
      + estimateSlippage(signal.size_requested, snapshot.spread)
      + estimateMarketImpact(signal.size_requested, snapshot.mid);

    result[latencyMs] = evRemaining > costs;
  }

  return result;
}

function computeSensitivity(
  signal: TradeSignal,
  snapshot: PriceSnapshot,
  edgeGross: number,
): ParameterSensitivity {
  const costs = FEE_RATE
    + estimateSlippage(signal.size_requested, snapshot.spread)
    + estimateMarketImpact(signal.size_requested, snapshot.mid);

  const basePnl = edgeGross - costs;

  // Threshold sensitivity: ±10% means edge would be ±10% different
  const thresholdMinus10 = edgeGross * 0.9 - costs;
  const thresholdPlus10 = edgeGross * 1.1 - costs;

  // Size sensitivity: costs scale with size
  const costsAt50Pct = FEE_RATE
    + estimateSlippage(signal.size_requested * 0.5, snapshot.spread)
    + estimateMarketImpact(signal.size_requested * 0.5, snapshot.mid);
  const costsAt150Pct = FEE_RATE
    + estimateSlippage(signal.size_requested * 1.5, snapshot.spread)
    + estimateMarketImpact(signal.size_requested * 1.5, snapshot.mid);

  const sizeMinus50 = (edgeGross - costsAt50Pct) * 0.5;
  const sizePlus50 = (edgeGross - costsAt150Pct) * 1.5;

  return {
    threshold_minus_10pct_pnl: thresholdMinus10,
    threshold_plus_10pct_pnl: thresholdPlus10,
    size_minus_50pct_pnl: sizeMinus50,
    size_plus_50pct_pnl: sizePlus50,
    robust: thresholdMinus10 > 0 && thresholdPlus10 > 0
      && sizeMinus50 > 0 && sizePlus50 > 0,
  };
}

function computeSensitivityResolved(record: ShadowRecord): ParameterSensitivity {
  const costs = record.cost_fees + record.cost_slippage + record.cost_market_impact;

  const basePnl = record.ideal_pnl;

  // At ±10% threshold, the signal might not have triggered or triggered sooner
  const thresholdMinus10 = basePnl * 0.9 - costs;
  const thresholdPlus10 = basePnl * 1.1 - costs;

  // Size sensitivity: scale PnL and variable costs
  const variableCosts = record.cost_slippage + record.cost_market_impact;
  const sizeMinus50 = (basePnl - record.cost_fees - variableCosts * 0.5) * 0.5;
  const sizePlus50 = (basePnl - record.cost_fees - variableCosts * 1.5) * 1.5;

  return {
    threshold_minus_10pct_pnl: thresholdMinus10,
    threshold_plus_10pct_pnl: thresholdPlus10,
    size_minus_50pct_pnl: sizeMinus50,
    size_plus_50pct_pnl: sizePlus50,
    robust: thresholdMinus10 > 0 && thresholdPlus10 > 0
      && sizeMinus50 > 0 && sizePlus50 > 0,
  };
}

function indexRecord(
  index: Map<string, string[]>,
  key: string,
  signalId: string,
): void {
  let ids = index.get(key);
  if (!ids) {
    ids = [];
    index.set(key, ids);
  }
  ids.push(signalId);
}
